nickname: "gaufre"
username: "gaufre"
password: "******"
server: "irc.example.com:6667"
channel: "#example"
admin_username: "example"
message_prefix: "ʕ　·ᴥ·ʔ < "
pushbullet_access_token: "****************"
pushbullet_user_email: "example@example.com"
